stages:
- test

cache:
  key: ${CI_COMMIT_SHA}
  paths:
  - .venv/

test:
  stage: test
  image: python:3.8.2-alpine3.11
  variables:
    POSTGRES_DB: payments_portmone
    POSTGRES_USER: payments_portmone
    POSTGRES_PASSWORD: payments_portmone
    POSTGRES_HOST: postgres
    PIPENV_VENV_IN_PROJECT: enabled
  services:
  - postgres:11.5-alpine
  before_script:
  - apk add build-base ca-certificates make git postgresql-libs postgresql-dev gcc musl-dev
  - pip install -U pip pipenv
  script:
  - pipenv sync --dev
  - pipenv run black --check .
  - pipenv run flake8
  - pipenv run pytest
